Feature/itm 302
IT-Minds/itm_mindster-service_web pull request #51
Opened 2021-03-17 10:41 UTC by mrb-itminds

depends on #50 

Added Service Library Page with ServiceCards placed in a responsive table

2021-03-21 13:25 UTC, objmj-itminds requested changes

2021-03-21 13:25 UTC, objmj-itminds commented on frontend/src/components/ServiceLibrary/ServiceLibrary.tsx
> +              )}
Scope the if a bit more like so
```
 <Box cursor="pointer">
   {!allShown ? "View all" : "Hide all"} ({services.length})
 </Box>
```

2021-03-21 13:25 UTC, objmj-itminds commented on frontend/src/components/ServiceLibrary/ServiceLibrary.tsx
> +            )}
Same here. I can only see the `.slice` being the difference, so scope the if down to that part
```
{(allShown ? services : services.slice(0,5)).map ... }
```

2021-03-22 07:24 UTC, mrb-itminds commented on frontend/src/components/ServiceLibrary/ServiceLibrary.tsx
> +              )}
Makes sense my bad ^^

2021-03-22 07:24 UTC, mrb-itminds commented on frontend/src/components/ServiceLibrary/ServiceLibrary.tsx
> +            )}
Makes sense my bad ^^

2021-03-22 08:16 UTC, objmj-itminds approved these changes

2021-03-22 08:16 UTC, merged