Feature/itm 330
IT-Minds/itm_mindster-service_web pull request #74
Opened 2021-04-06 13:33 UTC by mrb-itminds

depends on #66 
Functionality for the flow of inviting ActionApprovers. The person creating an action is automatically ActionApprover, and only he can invite additional approvers. 
Frontend wise it is a bit similar to inviting serviceOwner, though the approver overview is shown via a modal activated from a button in the action table rows.
All commands/queries are Unit tested.

2021-04-07 09:29 UTC, objmj-itminds requested changes
Minor adjustments.

2021-04-07 09:29 UTC, objmj-itminds commented on backend/Application/ActionApprovers/Commands/CreateActionApprovers/CreateActionApproverCommand.cs
> +          .Where(a => !_context.ActionApprovers.Any(e => e.Email == a.Email && e.ActionId == request.Id))
I would like this to be reversed so you do not make a DB lookup for each element in the input.

2021-04-07 09:29 UTC, objmj-itminds commented on frontend/src/components/Forms/Service/ActionApproverForm.tsx
> +    [approvers, newApprover]
You shouldn't need to recompute on `approvers` state change.

2021-04-07 09:29 UTC, objmj-itminds commented on frontend/src/components/ServiceScreen/Actions/ActionApprovers/ActionApproverOverview.tsx
> +    fetchData();
use `useEffectAsync` instead here.

2021-04-08 07:49 UTC, mrb-itminds commented on backend/Application/ActionApprovers/Commands/CreateActionApprovers/CreateActionApproverCommand.cs
> +          .Where(a => !_context.ActionApprovers.Any(e => e.Email == a.Email && e.ActionId == request.Id))
I tried this :
        var existingApprovers = _context.ActionApprovers.Where(e => e.ActionId == request.Id);
        var newApprovers = request.ActionApprovers
          .Where(a => !existingApprovers.Any(e => e.Email == a.Email))
          .Select(e => new ActionApprover
          {
            ActionId = request.Id,
            Email = e.Email
          });
not entirely reversed, but I only lookup in the DB once and filter based on actionId, and then use the filtered list to check for already existing actionApprovers.

I implemented this to create ServiceOwner and ApplicationOwner aswell since they used the same logic.

2021-04-08 07:53 UTC, mrb-itminds commented on frontend/src/components/Forms/Service/ActionApproverForm.tsx
> +    [approvers, newApprover]
Makes sense.

2021-04-08 08:09 UTC, mrb-itminds commented on frontend/src/components/ServiceScreen/Actions/ActionApprovers/ActionApproverOverview.tsx
> +    fetchData();
Ahh didn't see we had a custom hook for that

2021-04-21 13:49 UTC, objmj-itminds approved these changes

2021-04-21 13:49 UTC, merged